# Default values for consumer-chart

namespace:
  create: false
  name: kafka


  # Set labels for the application

labels:
  app: infra
  chart: infra-helm-chart
  release: infra

# Replica count for the application
replicaCount: 1
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 5

# Image details for the  consumer application 
image:
  repository: quay.io/csye-7125/consumerapp
  pullPolicy: IfNotPresent
  tag: 1.0.8

# Target port on which the consumer application is running
application:
  port: 3000

# Deployment strategies to be followed
deploymentStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
  minReadySeconds: 30
  progressDeadlineSeconds: 120

configMapName: consumer-configmap

# Override the values of postgresql subchart
postgresql:
  enabled: true
  auth:
    username: csye7125
    password: postgres
    database: consumer

# Schema used for the application
postgres:
  schema: public
  port: 5432
  username: csye7125
  password: postgres
  database: consumer

  primary:
      persistence:
      enabled: true
      size: 8Gi
      storageClass: standard
      accessMode: ReadWriteOnce

kafkavalues:
  brokers: 
    - infra-kafka-controller-0.infra-kafka-controller-headless.kafka.svc.cluster.local:9092
    - infra-kafka-controller-1.infra-kafka-controller-headless.kafka.svc.cluster.local:9092
    - infra-kafka-controller-2.infra-kafka-controller-headless.kafka.svc.cluster.local:9092
  topic: healthcheck
 
# Override the values of kafka subchart 
kafka:
    listeners:
      client: 
        protocol: PLAINTEXT
      controller:
        protocol: PLAINTEXT
    provisioning:
      enabled: true  
      numPartitions: 3  
      replicationFactor: 3
      topics:
        - name: healthcheck


resources:
  requests:
    memory: "512Mi"
    cpu: "350m"
  limits:
    memory: "1Gi"
    cpu: "500m"

# limits
limits:
    type: container
    default:
      memory: "1Gi"
      cpu: "500m"
    defaultRequest:
      memory: "1Gi"
      cpu: "500m"
    max:
      memory: "2Gi"
      cpu: "2"
 