apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name}}-consumer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "infra-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.deploymentStrategy.type }}
    rollingUpdate:
      maxSurge: {{ .Values.deploymentStrategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.deploymentStrategy.rollingUpdate.maxUnavailable }}
  minReadySeconds: {{ .Values.deploymentStrategy.minReadySeconds }}
  progressDeadlineSeconds: {{ .Values.deploymentStrategy.progressDeadlineSeconds }}
  selector:
    matchLabels:
      {{- include "infra-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "infra-chart.labels" . | nindent 8 }}

    spec:
      serviceAccountName: consumer-sa
      imagePullSecrets:
        - name: quay-creds
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: {{ .Values.application.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ .Values.configMapName }}
