apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kafka-consumer-role-binding
  namespace: kafka
subjects:
- kind: ServiceAccount
  name: consumer-sa
  namespace: kafka
roleRef:
  kind: Role
  name: kafka-consumer-role
  apiGroup: rbac.authorization.k8s.io
