apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kafka-consumer-role
  namespace: kafka
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
