apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJxdWF5LmlvIjp7InVzZXJuYW1lIjoicHVwcGFsYV9uIiwicGFzc3dvcmQiOiJRYXptYWdnaTEyM0AiLCJlbWFpbCI6InB1cHBhbGEubkBub3J0aGVhc3Rlcm4uZWR1IiwiYXV0aCI6ImNIVndjR0ZzWVY5dU9sRmhlbTFoWjJkcE1USXpRQT09In19fQ==
kind: Secret
metadata:
  name: regcred
  namespace: kafka
type: kubernetes.io/dockerconfigjson